name: Publish Consolidated File

on:
  schedule:
    - cron: "59 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies
        run: pnpm install
      - name: Consolidate
        run: pnpm tsx src/scripts/consolidate.ts
        env:
          STORAGE_AK: U0J0YOK82PFOQ0OQWGRB
          STORAGE_SK: ${{ secrets.SK_U0J0YOK82PFOQ0OQWGRB }}
          STORAGE_ENDPOINT: ap-south-1.linodeobjects.com
          STORAGE_BUCKET: jamulus-archive
          STORAGE_NS: main
